title: MFD-GG
description: Interaktif Rapor Okuma Platformu
theme: just-the-docs

url: https://emintavlayan.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
